"""create_epp_tables

Revision ID: 8d5a090697b0
Revises: b10c1487d65f
Create Date: 2026-02-04 09:23:11.867771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d5a090697b0'
down_revision: Union[str, Sequence[str], None] = 'b10c1487d65f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('certification', sa.String(length=100), nullable=True),
    sa.Column('assignment_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('useful_life_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_epp_id'), 'epp', ['id'], unique=False)
    op.create_index(op.f('ix_epp_serial_number'), 'epp', ['serial_number'], unique=True)
    op.create_table('epp_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('epp_id', sa.Integer(), nullable=False),
    sa.Column('inspection_date', sa.DateTime(), nullable=True),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('evidence_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['epp_id'], ['epp.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_epp_inspections_id'), 'epp_inspections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_epp_inspections_id'), table_name='epp_inspections')
    op.drop_table('epp_inspections')
    op.drop_index(op.f('ix_epp_serial_number'), table_name='epp')
    op.drop_index(op.f('ix_epp_id'), table_name='epp')
    op.drop_table('epp')
    # ### end Alembic commands ###
