"""add_missing_vehicle_fields

Revision ID: e72f7ff75a0c
Revises: 005_create_detailed_locations
Create Date: 2026-02-10 10:11:11.237914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e72f7ff75a0c'
down_revision: Union[str, Sequence[str], None] = '005_create_detailed_locations'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('movement_request_items', sa.Column('source_location_id', sa.Integer(), nullable=True))
    # op.add_column('movement_request_items', sa.Column('destination_location_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'movement_request_items', 'storage_locations', ['source_location_id'], ['id'])
    # op.create_foreign_key(None, 'movement_request_items', 'storage_locations', ['destination_location_id'], ['id'])
    # op.drop_index(op.f('idx_location_product'), table_name='product_location_assignments')
    # op.drop_index(op.f('idx_product_location'), table_name='product_location_assignments')
    # op.add_column('storage_locations', sa.Column('aisle', sa.String(length=50), nullable=True))
    # op.add_column('storage_locations', sa.Column('rack', sa.String(length=50), nullable=True))
    # op.add_column('storage_locations', sa.Column('shelf', sa.String(length=50), nullable=True))
    # op.add_column('storage_locations', sa.Column('position', sa.String(length=50), nullable=True))
    # op.add_column('storage_locations', sa.Column('location_type', sa.Enum('zone', 'aisle', 'rack', 'shelf', 'bin', 'pallet', 'floor', name='locationtype'), nullable=False))
    # op.add_column('storage_locations', sa.Column('capacity', sa.Integer(), nullable=True))
    # op.add_column('storage_locations', sa.Column('dimensions', sa.JSON(), nullable=True))
    # op.add_column('storage_locations', sa.Column('temperature_zone', sa.String(length=50), nullable=True))
    # op.drop_index(op.f('ix_locations_id'), table_name='storage_locations')
    # op.drop_index(op.f('uix_warehouse_code'), table_name='storage_locations')
    op.create_index(op.f('ix_storage_locations_id'), 'storage_locations', ['id'], unique=False)
    # op.create_unique_constraint('uix_warehouse_location_code', 'storage_locations', ['warehouse_id', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uix_warehouse_location_code', 'storage_locations', type_='unique')
    op.drop_index(op.f('ix_storage_locations_id'), table_name='storage_locations')
    # op.create_index(op.f('uix_warehouse_code'), 'storage_locations', ['warehouse_id', 'code'], unique=True)
    # op.create_index(op.f('ix_locations_id'), 'storage_locations', ['id'], unique=False)
    # op.drop_column('storage_locations', 'temperature_zone')
    # op.drop_column('storage_locations', 'dimensions')
    # op.drop_column('storage_locations', 'capacity')
    # op.drop_column('storage_locations', 'location_type')
    # op.drop_column('storage_locations', 'position')
    # op.drop_column('storage_locations', 'shelf')
    # op.drop_column('storage_locations', 'rack')
    # op.drop_column('storage_locations', 'aisle')
    # op.create_index(op.f('idx_product_location'), 'product_location_assignments', ['product_id', 'location_id'], unique=False)
    # op.create_index(op.f('idx_location_product'), 'product_location_assignments', ['location_id', 'product_id'], unique=False)
    # op.drop_constraint(None, 'movement_request_items', type_='foreignkey')
    # op.drop_constraint(None, 'movement_request_items', type_='foreignkey')
    # op.drop_column('movement_request_items', 'destination_location_id')
    # op.drop_column('movement_request_items', 'source_location_id')
    # ### end Alembic commands ###
