"""create_integrated_requests_tables

Revision ID: f550b5587fc9
Revises: 845ecbcd1053
Create Date: 2026-02-10 16:12:48.806369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f550b5587fc9'
down_revision: Union[str, Sequence[str], None] = '845ecbcd1053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrated_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_number', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Enum('PROYECTO', 'MANTENIMIENTO', 'OBRA', 'EMERGENCIA', 'OTRO', name='integratedrequestpurpose'), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=True),
    sa.Column('expected_return_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('BORRADOR', 'PENDIENTE', 'APROBADA', 'RECHAZADA', 'ENTREGADA', 'PARCIAL_DEVUELTA', 'COMPLETADA', name='integratedrequeststatus'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_by', sa.Integer(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('emergency_level', sa.Enum('NORMAL', 'URGENTE', 'CRITICA', name='emergencylevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrated_requests_id'), 'integrated_requests', ['id'], unique=False)
    op.create_index(op.f('ix_integrated_requests_request_number'), 'integrated_requests', ['request_number'], unique=True)
    op.create_table('request_epp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('epp_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('expected_return_date', sa.Date(), nullable=True),
    sa.Column('checkout_date', sa.DateTime(), nullable=True),
    sa.Column('checkin_date', sa.DateTime(), nullable=True),
    sa.Column('condition_out', sa.String(length=50), nullable=True),
    sa.Column('condition_in', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDIENTE', 'ASIGNADO', 'DEVUELTO', 'CADUCADO', 'DANADO', name='requesteppstatus'), nullable=True),
    sa.Column('inspection_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['epp_id'], ['epp.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['integrated_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_epp_id'), 'request_epp', ['id'], unique=False)
    op.create_table('request_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('quantity_requested', sa.Integer(), nullable=False),
    sa.Column('quantity_approved', sa.Integer(), nullable=True),
    sa.Column('quantity_delivered', sa.Integer(), nullable=True),
    sa.Column('quantity_returned', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDIENTE', 'APROBADO', 'ENTREGADO', 'DEVUELTO_PARCIAL', 'CONSUMIDO', name='requestitemstatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['product_batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['integrated_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_items_id'), 'request_items', ['id'], unique=False)
    op.create_table('request_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('PRODUCTO', 'HERRAMIENTA', 'EPP', 'VEHICULO', name='requesttrackingitemtype'), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('SOLICITADO', 'APROBADO', 'ENTREGADO', 'RECORDATORIO', 'VENCIDO', 'DEVUELTO', name='requesttrackingaction'), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['integrated_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_tracking_id'), 'request_tracking', ['id'], unique=False)
    op.create_table('request_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('odometer_out', sa.Integer(), nullable=True),
    sa.Column('odometer_in', sa.Integer(), nullable=True),
    sa.Column('fuel_level_out', sa.Enum('LEVEL_0_25', 'LEVEL_25_50', 'LEVEL_50_75', 'LEVEL_75_100', name='fuellevel'), nullable=True),
    sa.Column('fuel_level_in', sa.Enum('LEVEL_0_25', 'LEVEL_25_50', 'LEVEL_50_75', 'LEVEL_75_100', name='fuellevel'), nullable=True),
    sa.Column('checkout_date', sa.DateTime(), nullable=True),
    sa.Column('checkin_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDIENTE', 'ASIGNADO', 'EN_USO', 'DEVUELTO', 'CON_INCIDENTE', name='requestvehiclestatus'), nullable=True),
    sa.Column('incident_report', sa.Text(), nullable=True),
    sa.Column('return_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['integrated_requests.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_vehicles_id'), 'request_vehicles', ['id'], unique=False)
    op.create_table('request_tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('expected_return_date', sa.Date(), nullable=True),
    sa.Column('condition_out', sa.String(length=50), nullable=True),
    sa.Column('condition_in', sa.String(length=50), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDIENTE', 'PRESTADA', 'DEVUELTA', 'DANADA', 'PERDIDA', name='requesttoolstatus'), nullable=True),
    sa.Column('damage_notes', sa.Text(), nullable=True),
    sa.Column('penalty_applied', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['integrated_requests.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_tools_id'), 'request_tools', ['id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_applied_at'), 'ledger_entries', ['applied_at'], unique=False)
    op.create_index(op.f('ix_ledger_entries_id'), 'ledger_entries', ['id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_product_id'), 'ledger_entries', ['product_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_warehouse_id'), 'ledger_entries', ['warehouse_id'], unique=False)
    # op.drop_index(op.f('uix_warehouse_code'), table_name='storage_locations')
    # op.create_unique_constraint('uix_warehouse_location_code', 'storage_locations', ['warehouse_id', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_warehouse_location_code', 'storage_locations', type_='unique')
    op.create_index(op.f('uix_warehouse_code'), 'storage_locations', ['warehouse_id', 'code'], unique=True)
    op.drop_index(op.f('ix_ledger_entries_warehouse_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_product_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_applied_at'), table_name='ledger_entries')
    op.drop_index(op.f('ix_request_tools_id'), table_name='request_tools')
    op.drop_table('request_tools')
    op.drop_index(op.f('ix_request_vehicles_id'), table_name='request_vehicles')
    op.drop_table('request_vehicles')
    op.drop_index(op.f('ix_request_tracking_id'), table_name='request_tracking')
    op.drop_table('request_tracking')
    op.drop_index(op.f('ix_request_items_id'), table_name='request_items')
    op.drop_table('request_items')
    op.drop_index(op.f('ix_request_epp_id'), table_name='request_epp')
    op.drop_table('request_epp')
    op.drop_index(op.f('ix_integrated_requests_request_number'), table_name='integrated_requests')
    op.drop_index(op.f('ix_integrated_requests_id'), table_name='integrated_requests')
    op.drop_table('integrated_requests')
    # ### end Alembic commands ###
